<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1599" started-at="2020-06-30T11:17:43Z" finished-at="2020-06-30T11:17:45Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1599" started-at="2020-06-30T11:17:43Z" finished-at="2020-06-30T11:17:45Z">
      <class name="testcases.TestCase">
        <test-method status="PASS" signature="setReport()[pri:0, instance:testcases.TestCase@68be2bc2]" name="setReport" is-config="true" duration-ms="485" started-at="2020-06-30T11:17:43Z" finished-at="2020-06-30T11:17:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setReport -->
        <test-method status="PASS" signature="doLogin()[pri:0, instance:testcases.TestCase@68be2bc2]" name="doLogin" duration-ms="28" started-at="2020-06-30T11:17:43Z" finished-at="2020-06-30T11:17:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="teadDown(org.testng.ITestResult)[pri:0, instance:testcases.TestCase@68be2bc2]" name="teadDown" is-config="true" duration-ms="32" started-at="2020-06-30T11:17:44Z" finished-at="2020-06-30T11:17:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=doLogin status=SUCCESS method=TestCase.doLogin()[pri:0, instance:testcases.TestCase@68be2bc2] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teadDown -->
        <test-method status="FAIL" signature="registration()[pri:0, instance:testcases.TestCase@68be2bc2]" name="registration" duration-ms="12" started-at="2020-06-30T11:17:44Z" finished-at="2020-06-30T11:17:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test registration failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test registration failed
at org.testng.Assert.fail(Assert.java:96)
at testcases.TestCase.registration(TestCase.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registration -->
        <test-method status="PASS" signature="teadDown(org.testng.ITestResult)[pri:0, instance:testcases.TestCase@68be2bc2]" name="teadDown" is-config="true" duration-ms="1" started-at="2020-06-30T11:17:44Z" finished-at="2020-06-30T11:17:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=registration status=FAILURE method=TestCase.registration()[pri:0, instance:testcases.TestCase@68be2bc2] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teadDown -->
        <test-method status="SKIP" signature="sendMail()[pri:0, instance:testcases.TestCase@68be2bc2]" name="sendMail" duration-ms="5" started-at="2020-06-30T11:17:44Z" finished-at="2020-06-30T11:17:44Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Test sending email is skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Test sending email is skipped
at testcases.TestCase.sendMail(TestCase.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sendMail -->
        <test-method status="PASS" signature="teadDown(org.testng.ITestResult)[pri:0, instance:testcases.TestCase@68be2bc2]" name="teadDown" is-config="true" duration-ms="1" started-at="2020-06-30T11:17:44Z" finished-at="2020-06-30T11:17:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=sendMail status=SKIP method=TestCase.sendMail()[pri:0, instance:testcases.TestCase@68be2bc2] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teadDown -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:testcases.TestCase@68be2bc2]" name="endReport" is-config="true" duration-ms="980" started-at="2020-06-30T11:17:44Z" finished-at="2020-06-30T11:17:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- testcases.TestCase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
